# Generated by Django 6.0 on 2026-01-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empinfo',
            fields=[
                ('employeeid', models.AutoField(primary_key=True, serialize=False)),
                ('employeename', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=20)),
                ('mob_no', models.BigIntegerField()),
            ],
            options={
                'db_table': 'empinfo',
            },
        ),
    ]
