# Generated by Django 6.0 on 2026-01-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empinfo',
            old_name='mob_no',
            new_name='mobno',
        ),
    ]
