# Generated by Django 6.0 on 2026-01-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employeeapp', '0002_rename_mob_no_empinfo_mobno'),
    ]

    operations = [
        migrations.AddField(
            model_name='empinfo',
            name='employeeemail',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
