# Generated by Django 6.0 on 2026-06-22 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employeeapp', '0003_empinfo_employeeemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='empinfo',
            name='date_of_joining',
            field=models.DateField(default=datetime.date(2026, 6, 22)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empinfo',
            name='department',
            field=models.CharField(default='General', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empinfo',
            name='designation',
            field=models.CharField(default='Employee', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empinfo',
            name='salary',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='mobno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
