# Generated by Django 6.0 on 2026-06-22 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employeeapp', '0004_empinfo_date_of_joining_empinfo_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empinfo',
            name='date_of_joining',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='department',
            field=models.CharField(default='General', max_length=250),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='designation',
            field=models.CharField(default='Employee', max_length=250),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='employeeid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
