# Generated by Django 6.0 on 2026-06-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employeeapp', '0005_alter_empinfo_date_of_joining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empinfo',
            name='employeeid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
